### ISSUE TITLE
Is not deploying to Bluemix via One Button Deploy

### ISSUE THREAD

**Issue by benrondeau** [IBM-Bluemix/MeanJS#1]
Just hangs on the deployment phase when you use the One Button Deploy. Manual build/upload works fine. @ryanjbaxter will look into it.

**Comment by ryanjbaxter** [comment]
I just did a deploy with the button from the repo and it worked fine for me, the running app can be seen here.

http://mean-rjbaxter-1551.mybluemix.net/

Can you give me access to your repo so I can look at the deployment pipeline?  Maybe it was a problem with DevOps services rather than the code itself?

**Comment by rvennam** [comment]
Works for me too.

**Comment by benrondeau** [comment]
Working for me now to. Thanks
